name: rit_parking
description: "A Flutter App for RIT Parking Services."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  http: ^1.2.1
  csv: ^6.0.0
  numberpicker: ^2.1.2
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/user_data.csv